package com.fkistner.SouthQuay.UI;

import org.fife.ui.rsyntaxtextarea.*;
import org.fife.ui.rtextarea.Gutter;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import java.awt.*;

/**
 * UI builder designed super class of the Editor controller.
 */
public class EditorBase {
    protected JPanel rootPanel;
    protected JScrollPane scrollPane;
    protected RSyntaxTextArea syntaxTextArea;
    protected JTextPane outputTextPane;
    protected JButton evaluateButton;
    protected JButton abortButton;
    protected JLabel statusLabel;
    protected ErrorStrip errorStrip;

    /**
     * Creates some of the UI components using custom logic.
     */
    private void createUIComponents() {
        syntaxTextArea = new RSyntaxTextArea();
        syntaxTextArea.setCodeFoldingEnabled(true);
        Font font = syntaxTextArea.getFont();

        FontUIResource fontUIResource = (FontUIResource) UIManager.get("TextPane.font");
        if (fontUIResource != null) { // Derive font size from default text pane font size to better support Windows DPI settings
            font = font.deriveFont(font.getSize2D() / 13f * fontUIResource.getSize2D());
            syntaxTextArea.setFont(font);
        }

        outputTextPane = new JTextPane();
        outputTextPane.setFont(font);

        errorStrip = new ErrorStrip(syntaxTextArea);

        Gutter gutter = new Gutter(syntaxTextArea);
        gutter.setLineNumberFont(font);
        gutter.setLineNumberColor(SyntaxColors.getSecondaryColor());
        scrollPane = new JScrollPane();
        scrollPane.setRowHeaderView(gutter);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setPreferredSize(new Dimension(800, 800));
        errorStrip.setShowMarkAll(true);
        errorStrip.setShowMarkedOccurrences(true);
        rootPanel.add(errorStrip, BorderLayout.EAST);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel1, BorderLayout.CENTER);
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        panel1.add(toolBar1, BorderLayout.SOUTH);
        statusLabel = new JLabel();
        toolBar1.add(statusLabel);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        toolBar1.add(panel2);
        evaluateButton = new JButton();
        evaluateButton.setText("▶");
        toolBar1.add(evaluateButton);
        abortButton = new JButton();
        abortButton.setText("◼");
        abortButton.setVisible(false);
        toolBar1.add(abortButton);
        scrollPane.setHorizontalScrollBarPolicy(31);
        scrollPane.setVerticalScrollBarPolicy(22);
        panel1.add(scrollPane, BorderLayout.CENTER);
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(true);
        splitPane1.setDividerLocation(400);
        splitPane1.setResizeWeight(1.0);
        scrollPane.setViewportView(splitPane1);
        splitPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        final FixedWidthScrollPane fixedWidthScrollPane1 = new FixedWidthScrollPane();
        fixedWidthScrollPane1.setVerticalScrollBarPolicy(21);
        splitPane1.setLeftComponent(fixedWidthScrollPane1);
        fixedWidthScrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        syntaxTextArea.setCurrentLineHighlightColor(new Color(-328966));
        syntaxTextArea.setPaintMatchedBracketPair(true);
        syntaxTextArea.setPaintTabLines(true);
        syntaxTextArea.setTabsEmulated(true);
        syntaxTextArea.setWhitespaceVisible(true);
        fixedWidthScrollPane1.setViewportView(syntaxTextArea);
        final FixedWidthScrollPane fixedWidthScrollPane2 = new FixedWidthScrollPane();
        fixedWidthScrollPane2.setVerticalScrollBarPolicy(21);
        splitPane1.setRightComponent(fixedWidthScrollPane2);
        fixedWidthScrollPane2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        outputTextPane.setBackground(new Color(-1644826));
        outputTextPane.setEditable(false);
        fixedWidthScrollPane2.setViewportView(outputTextPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
