package com.fkistner.SouthQuay.UI;

import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * Created by florian on 7/12/17.
 */
public class EditorBase {
    protected JPanel panel;
    protected JScrollPane scrollPane;
    protected RSyntaxTextArea syntaxTextArea;
    protected RSyntaxTextArea outputTextArea;
    protected JButton evaluateButton;
    protected JButton abortButton;
    protected JLabel statusLabel;
    protected Gutter gutter;


    private void createUIComponents() {
        syntaxTextArea = new RSyntaxTextArea();
        syntaxTextArea.setCodeFoldingEnabled(true);

        Font defaultFont = new Font("Monospaced", Font.PLAIN, 12);
        gutter = new Gutter(syntaxTextArea);
        gutter.setLineNumberFont(defaultFont);
        gutter.setLineNumberColor(Color.GRAY);
        gutter.setBookmarkingEnabled(true);
        scrollPane = new JScrollPane();
        scrollPane.setRowHeaderView(gutter);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        panel.setPreferredSize(new Dimension(600, 600));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        panel.add(toolBar1, BorderLayout.SOUTH);
        statusLabel = new JLabel();
        toolBar1.add(statusLabel);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        toolBar1.add(panel1);
        evaluateButton = new JButton();
        evaluateButton.setText("▶");
        toolBar1.add(evaluateButton);
        abortButton = new JButton();
        abortButton.setText("◼");
        abortButton.setVisible(false);
        toolBar1.add(abortButton);
        panel.add(scrollPane, BorderLayout.CENTER);
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(true);
        splitPane1.setDividerLocation(358);
        splitPane1.setResizeWeight(0.618);
        scrollPane.setViewportView(splitPane1);
        syntaxTextArea.setPaintMatchedBracketPair(true);
        syntaxTextArea.setPaintTabLines(true);
        syntaxTextArea.setTabsEmulated(true);
        syntaxTextArea.setWhitespaceVisible(true);
        splitPane1.setLeftComponent(syntaxTextArea);
        outputTextArea = new RSyntaxTextArea();
        outputTextArea.setBackground(new Color(-1644826));
        outputTextArea.setEditable(false);
        outputTextArea.setHighlightCurrentLine(false);
        outputTextArea.setPreferredSize(new Dimension(200, 15));
        splitPane1.setRightComponent(outputTextArea);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
